name: samirnet_videos
description: SamirNet Videos - Flutter media link manager
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.3.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  shared_preferences: ^2.3.2
  sqflite: ^2.4.1
  path: ^1.9.0
  path_provider: ^2.1.5
  url_launcher: ^6.3.1
  share_plus: ^10.1.4
  http: ^1.2.2
  video_player: ^2.9.2
  permission_handler: ^11.3.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
flutter:
  uses-material-design: true
